### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m3-evaluacion-intermedia-AnaAmaro#1]
Buen trabajo @AnaAmaro  !

Algunas pistas para acabarlo:

- [ ] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes

Muy muy buen curro!

Veo que buscas el sobre saliente y está de sobre saliente!!! Pero recuerda que antes de buscar el sobre saliente hay que buscar el aprobado, el bien y el notable. Pasar de 0 a 10 es muy frustrante.
Si tienes cualquier duda, avisa!

Al turrón

**Comment by AnaAmaro** [comment]
@migueldelmazo , listo señor, ya está terminado el ejercicio, a ver que le parece. Hay estilos en css que no los termina de renderizar, y eso que le estoy haciendo un npm run build, pero bueno, son detalles secundarios.

**Comment by migueldelmazo** [comment]
Aquí lo tienes @AnaAmaro, muy bien hecho.

**Comment by AnaAmaro** [comment]
➕ Add functions:

✔️ PokeFilter.js component, to filter PokeName.
✔️ Change background-color by clicking on any of the cards.
✔️ Add componentDidMount.
🔸 I have created a function to add favorites but i have problems to make it work completely. Could you check my code and help me with that? Thanks.
